
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abdallah Okasha
 */
public class Loyedmax extends javax.swing.JFrame {

    /**
     * Creates new form Loyedmax
     */
        double avg=0.0;
        int num=0;
        String n="";
        BufferedReader br = null;
        ArrayList<Double> input = new ArrayList<Double>();
        ArrayList<ArrayList<Double>> allAvgs  = new ArrayList<ArrayList<Double>>();
        ArrayList<String> binCode = new ArrayList<String>();
        ArrayList<Double> lw = new ArrayList<Double>();
        ArrayList<Double> up = new ArrayList<Double>(); 
        ArrayList<Double> deComp = new ArrayList<Double>();
        public Loyedmax() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Num Of Bits");

        jRadioButton1.setText("Quantization");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("De_Quantization");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Loyedmax");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(jRadioButton2)
                        .addGap(58, 58, 58))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         jRadioButton2.setSelected(true);
         jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if(jRadioButton1.isSelected()){
       n=jTextField1.getText();
       num=Integer.parseInt(n);
       //===<< Compress >>===
       //Reading begin     
       String tmp="";
       try {
            String sCurrentLine="";
            br = new BufferedReader(new FileReader("D:\\Java\\Loyedmax\\input.txt"));

            while ((sCurrentLine = br.readLine()) != null) {
                //System.out.print(sCurrentLine + " ");
                //double value = Double.parseDouble(sCurrentLine);
                //input.add(value);
                tmp=sCurrentLine;
            }

        } catch (IOException e) {
        } finally {
            try {
                if (br != null) {
                    br.close();
                }
            } catch (IOException ex) {
            }
        }
        //Create binary code
        double level = Math.pow(2.00, num);
        for (int i = 0; i < level; i++) {
            String bin = Integer.toBinaryString(i);
            if (bin.length() != num) {
                for (int j = bin.length(); j < num; j++) {
                    bin = '0' + bin;
                }
            }
            System.out.println(bin);
            binCode.add(bin);
        } 
       //fill input in Arraylist
        String[] arrStr=tmp.split(" ");
        for (int i=0;i<arrStr.length;i++){
            input.add(Double.parseDouble(arrStr[i]));
        }
        //for (int i=0;i<input.size();i++)
        //{System.out.print(input.get(i)+ " ");}
        //==End of Reading
       //Collections.sort(input);
       //==============================
        // <<Create Ranges and Split n Bits>>
       double sum=0.0;
       double avg=0.0;
       for (int i=0;i<input.size();i++){
       sum+=input.get(i);
       }
       avg=sum/input.size();
       //System.out.println(sum + " " + avg);
       //ArrayList<Double> curAvgs = new ArrayList<Double>();
       ArrayList<Double> prevAvgs = new ArrayList<Double>();
       prevAvgs.add(avg);
       allAvgs.add(prevAvgs);
       for (int i=0;i<num;i++){
        ArrayList<Double> curAvgs = new ArrayList<Double>();
        for (int j=0;j<allAvgs.get(allAvgs.size()-1).size();j++){
                 double a=allAvgs.get(allAvgs.size()-1).get(j);
                 int b=(int)(a);
                 if (a==b)
                 {curAvgs.add(a-1.00);
                 curAvgs.add(a+1.00);}
                 else {
                 curAvgs.add(b+0.0);
                 curAvgs.add(b+1.00);}
       }
       //allAvgs.add(curAvgs);
       double[] mySum = new double[1000];
       int[] myCnt = new int[1000];
       //==
       for(int p=0;p<mySum.length;p++)
       {mySum[p] = 0.0;}
       for(int p=0;p<myCnt.length;p++)
       {myCnt[p] = 0;}
       //==
          for (int f=0;f<input.size();f++){
          int pos=0;double mn=1000000.00;   
       for (int k=0;k<curAvgs.size();k++){
           double def=input.get(f)-curAvgs.get(k);
           if (def<0)def*=-1;
           if (def<mn){
           mn=def;pos=k;
           }
       }
       mySum[pos]+=input.get(f);
       myCnt[pos]++;
          }
       for (int y=0;y<curAvgs.size();y++){
       curAvgs.set(y, (mySum[y]/myCnt[y]));
       }
       allAvgs.add(curAvgs);
       }
       //Print allAvgs
       for (int i=0;i<allAvgs.size();i++){
           for (int j=0;j<allAvgs.get(i).size();j++){
               System.out.print(allAvgs.get(i).get(j)+ " ");
           }
           System.out.println("");
       }
            
            System.out.println("<< Ranges >>");
            double prev=0.0;
            for (int i=0;i<allAvgs.get(allAvgs.size()-1).size()-1;i++){
                double a=allAvgs.get(allAvgs.size()-1).get(i);
                double sumt=(int)a;
                a=allAvgs.get(allAvgs.size()-1).get(i+1);
                sumt+=(int)a;
                lw.add(prev);
                up.add(sumt/2);
                prev=sumt/2;
                //System.out.println(prev + " "+(sumt/2));
            }
            lw.add(up.get(up.size()-1));
            up.add(allAvgs.get(allAvgs.size()-1).get(allAvgs.get(allAvgs.size()-1).size()-1));
            for (int i=0;i<lw.size();i++){
                System.out.println(lw.get(i)+ " -> " + up.get(i));
            }
            String comp="";
            
            for (int i=0;i<input.size();i++){
                int pos=0;
                if (input.get(i)>=up.get(up.size()-1)){pos=up.size()-1;}
                else 
                for (int j=0;j<lw.size();j++){
                    if (input.get(i)>=lw.get(j)&&input.get(i)<=up.get(j)){pos=j;break;}
                }
                comp=comp+binCode.get(pos);
                double tmpp=allAvgs.get(allAvgs.size()-1).get(pos);
                int tm=(int)tmpp;
                deComp.add(tm*1.00);
            }
            System.out.println("Compression : "+comp);
            System.out.println("Decompress : ");
            for (int i=0;i<deComp.size();i++){
                System.out.print( deComp.get(i)+" ");
            }
       }//End of Compress
       //De-compress 
       else if(jRadioButton2.isSelected()){
                n=jTextField1.getText();
         num=Integer.parseInt(n);
         //===<< De-Compress >>=== 
         System.out.println("");
         System.out.println("Decompress : ");
            for (int i=0;i<deComp.size();i++){
                System.out.print( deComp.get(i)+" ");   
        }
            System.out.println("");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
         jRadioButton1.setSelected(true);
         jRadioButton2.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loyedmax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loyedmax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loyedmax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loyedmax.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loyedmax().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
//